# Generated by Django 4.1.3 on 2022-11-27 17:35

import articleapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_publish", "created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=articleapp.models.generate_random_slug),
        ),
    ]
