# Generated by Django 4.1.3 on 2022-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0002_alter_post_options_post_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_user_slug"
            ),
        ),
    ]
