# Generated by Django 4.1.3 on 2022-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
