# Generated by Django 4.1.3 on 2022-11-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0006_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_publish",
            field=models.DateField(blank=True, null=True),
        ),
    ]
