# Generated by Django 4.1.3 on 2022-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0007_alter_post_date_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(max_length=100, null=True, verbose_name="ニックネーム"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                null=True, upload_to="uploads/", verbose_name="プロフィール画像"
            ),
        ),
    ]
