# Generated by Django 4.1.3 on 2022-12-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0009_alter_post_body_alter_post_slug_alter_post_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, verbose_name="本文"),
        ),
    ]
