# Generated by Django 4.1.3 on 2022-12-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0010_alter_post_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_publish", "-created_at"]},
        ),
    ]
