# Generated by Django 4.1.3 on 2022-12-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0012_alter_post_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "タグ", "verbose_name_plural": "タグ"},
        ),
    ]
